// ── Textos en español para AG Grid ───────────────────────────────────────────
// AG Grid es una librería en inglés; este objeto sobreescribe cada texto
// de la interfaz (paginación, filtros, menús) con su traducción en español.
export const LOCALE_SPANISH = {
  page: 'Página',
  more: 'Más',
  to: 'a',
  of: 'de',
  pageLastRowUnknown: 'última',
  notPinned: 'Sin anclar',
  pinned: 'Anclado',
  pivotChartAndPivotTable: 'Gráfico y tabla dinámica',
  pivotTable: 'Tabla dinámica',
  pivotChart: 'Gráfico dinámico',
  pinLeft: 'Anclar a la izquierda',
  pinRight: 'Anclar a la derecha',
  noData: 'Sin datos para mostrar',
  enabled: 'Habilitado',
  disabled: 'Deshabilitado',
  sortAscending: 'Ordenar de menor a mayor',
  sortDescending: 'Ordenar de mayor a menor',
  sortBy: 'Ordenar por',
  apply: 'Aplicar',
  clear: 'Limpiar',
  reset: 'Restablecer',
  search: 'Buscar',
  blanks: 'En blanco',
  filterOoo: 'Filtrar...',
  equals: 'Igual a',
  notEqual: 'No igual a',
  lessThan: 'Menor que',
  greaterThan: 'Mayor que',
  lessThanOrEqual: 'Menor o igual a',
  greaterThanOrEqual: 'Mayor o igual a',
  inRange: 'En rango',
  inRangeStart: 'Inicio',
  inRangeEnd: 'Fin',
  greaterThanAndLessThan: 'Mayor que y menor que',
  contains: 'Contiene',
  notContains: 'No contiene',
  startsWith: 'Comienza con',
  endsWith: 'Termina con',
  filtersToolPanelHeader: 'Filtros',
  selectAll: 'Seleccionar todo',
  selectAllFilteredResults: 'Seleccionar todos los resultados filtrados',
  addCurrentSelectionToFilter: 'Agregar la selección actual al filtro',
  clearCurrentSelection: 'Limpiar la selección actual',
  nothingSelected: 'Nada seleccionado',
}

// ── Propiedades por defecto para todas las columnas ───────────────────────────
// Se aplica a cada columna que no sobreescriba explícitamente estos valores.
export const DEFAULT_COL_DEF = {
  sortable:   true,
  filter:     true,
  resizable:  true,
}
